spring:
  application:
    name: megastore
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
  datasource:
    url: jdbc:mysql://${DATASOURCE_URL:localhost:3306/megastore}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: ${SPRING_PROFILE:development}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:7up.megastore@gmail.com}
    password: ${MAIL_PASSWORD:kemb pmbj helh ikvn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true