spring:
  application:
    name: megastore
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
  datasource:
    url: jdbc:mysql://${DATASOURCE_URL:localhost:3306/megastore}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:martin1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: ${SPRING_PROFILE:development}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

frontend:
  url: ${FRONTEND_URL}

app:
  url: ${APP_URL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
